### ISSUE TITLE
Unable to generate PDF

### ISSUE THREAD

**Issue by wimdeblauwe** [mraible/infoq-mini-book#10]
I am trying to use `generate-pdf.sh` to generate a PDF, but it does not work.

I first ran `rvm install "ruby-2.3.1"` to install the required Ruby version. But then things failed with:

To install the version of bundler this project requires, run `gem install bundler -v '< 2'`

So I ran `gem install bundler -v '< 2'`, but now I get:

```
Bundler::GemNotFound: Could not find Ascii85-1.0.3 in any of the sources
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize'
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
  /Users/wdb/.rvm/gems/ruby-2.3.1/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
  /Users/wdb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /Users/wdb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Could not find Ascii85-1.0.3 in any of the sources
Run `bundle install` to install missing gems.
./generate-pdf.sh: line 55: bundler:: command not found
```

So I ran `bundle install`

And now I get:

```
asciidoctor: WARNING: skipping reference to missing attribute: snippetsdirectory
asciidoctor: WARNING: skipping reference to missing attribute: snippetsdirectory
/Users/wdb/Projects/infoq-mini-book/.bundle/gems/ruby/2.3.0/bundler/gems/asciidoctor-pdf-03ceac32e426/bin/optimize-pdf: line 51: gs: command not found
```

What is this `gs` command and how do I install it?

**Comment by mraible** [comment]
I’ve seen this before. I’d try “brew install gs” if you’re on a Mac.

**Comment by wimdeblauwe** [comment]
Thx, that works. So to summarize to anyone else that wants to do this: these are all the commands (for macOS):

1. `rvm install "ruby-2.3.1"`
2. `gem install bundler -v '< 2'`
3. `bundle install`
4. `brew install gs`

**Comment by mraible** [comment]
If you have time, can you create a PR to add this to the README?

**Comment by wimdeblauwe** [comment]
PR #12 created for this.

**Comment by mraible** [comment]
Thanks!
