### ISSUE TITLE
Question: how to run this project in Windows

### ISSUE THREAD

**Issue by menglun** [mraible/infoq-mini-book#2]
I was able to run the build.sh in Linux successfully. But Is there an equivalent batch command that I can run in Windows? Thanks!

**Comment by menglun** [comment]
When I ran "gradlew clean all --stacktrace", I got following errors:

:pdf FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pdf'.
> (LoadError) no such file to load -- C/Users/238004/Downloads/infoq-mini-book-master/src/main/ruby/asciidoctor-pdf-extensions

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':pdf'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- C/Users/238004/Downloads/infoq-mini-book-master/src/main/ruby/asciidoctor-pdf-extensions
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:939)
        at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54)
        at RUBY.<top>(<script>:1)


BUILD FAILED

**Comment by mraible** [comment]
For Windows, you could try installing [bash on Windows 10](http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/). I'm not sure why `asciidoctor-pdf-extensions` is failing to load. Any ideas @mojavelinux?

**Comment by mojavelinux** [comment]
It appears the path is being calculated wrong on Windows. In the error message, I see `C/Users` which Ruby probably doesn't understand. I'm not sure why it is showing up that way since the `file` function in Gradle is supposed to create the correct path. That's where I'd focus. Try to use a hard-coded path and see if that works. That will tell us what we need to know.

```
require 'C:/Users/238004/Downloads/infoq-mini-book-master/src/main/ruby/asciidoctor-pdf-extensions.rb'
```

**Comment by mojavelinux** [comment]
Gradle and Ruby should have no problem working on Windows, so while installing Bash would make the environment more like Linux, it shouldn't be required.

**Comment by menglun** [comment]
@mojavelinux , thanks for your response! However I tried the following path format, but none of them work.

`C:/Users/238004/Downloads/infoq-mini-book-master/src/main/ruby/asciidoctor-pdf-extensions.rb
C:\\Users\\238004\\Downloads\\infoq-mini-book-master\\src\\main\\ruby\\asciidoctor-pdf-extensions.rb
file:///C:/Users/238004/Downloads/infoq-mini-book-master/src/main/ruby/asciidoctor-pdf-extensions.rb`

**Comment by mojavelinux** [comment]
Ruby understands forward slashes on Windows, so you can write paths as `C:/Users/...` and it will work.

However, it seems we have a different (or perhaps a secondary) issue ;)

**Comment by mojavelinux** [comment]
Can you confirm that `C:/Users/238004/Downloads/infoq-mini-book-master/src/main/ruby/asciidoctor-pdf-extensions.rb` resolves to a file?

In order to help further, I'll need to fire up Windows. Otherwise, I'm just guessing.

**Comment by menglun** [comment]
No, 'C:/Users/238004/Downloads/infoq-mini-book-master/src/main/ruby/asciidoctor-pdf-extensions.rb' does not resolve to a correct file path. I got the same error message. 

>Execution failed for task ':pdf'.
>(LoadError) no such file to load -- C/Users/238004/Downloads/infoq-mini-book-master/src/main/ruby/asciidoctor-pdf-extensions

Thank for helping out.

**Comment by mojavelinux** [comment]
What I'm asking is whether that path exists on your system, not whether Ruby can resolve it. If you navigate in the File Explorer, does that path resolve to a file?

**Comment by menglun** [comment]
Yes, it does resolve to a file.

**Comment by mojavelinux** [comment]
Thank you.

**Comment by mojavelinux** [comment]
I think this was due to a bug in the Gradle plugin. The file path passed to `requires` was being sanitized. The development version of the plugin no longer does this, so we are just waiting on a release.

**Comment by mraible** [comment]
@menglun Can you please try the latest version on `master` and see if you still have issues?
